### PR TITLE
Remove security for did.json

### PR DESCRIPTION
**Pull request by nissimsan**
Getting rid of the lock: 
image

### CODE REVIEW

**Review by BenjaminMoe — APPROVED** [review]

**Review by BenjaminMoe — APPROVED** [review]

**Review by mprorock — CHANGES_REQUESTED** [review]
Did.json should be optional - it is a MAY

**Comment by nissimsan** [comment]
@mprorock, no we landed on MUST NOT: 
https://github.com/w3c-ccg/traceability-interop/issues/252#issuecomment-1182184548

**Comment by BenjaminMoe** [comment]
@mprorock Requiring OAuth2 on `/did.json` would make `did:web` unresolvable.

**Review by OR13 — CHANGES_REQUESTED** [review]
This would break did:web.

**Review by OR13 — APPROVED** [review]
Ahh i read this wrong way, see the did web spec, this endpoint needs to be resolvable via GET, with no auth.

**Review by mprorock — APPROVED** [review]
revisted spec - lgtm

**Pull request merged**
