### PR TITLE
feat: transmute interop creds

### PR DESCRIPTION
**Pull request by nissimsan**

### CODE REVIEW

**Review by mprorock — APPROVED** [review]

**Comment by mprorock** [comment]
your config, trust it is good :)

**Comment by nissimsan** [comment]
@brownoxford, this should align to a corresponding secret I've created. Note that I changed the baseURL to our commercial environment. 
@OR13 FYI too. 
Can't wait to run this once the switch to did:web has been made...!

**Review by OR13 — APPROVED** [review]

**Comment by OR13** [comment]
related, we can also wire this up: https://github.com/transmute-industries/api.did.actor/pull/4

It does not require authentication, and it does support web discoverability.... we can handle it in a separate PR, but I hope it may assist anyone trying to test this stuff.

**Comment by nissimsan** [comment]
> related, we can also wire this up: [transmute-industries/api.did.actor#4](https://github.com/transmute-industries/api.did.actor/pull/4)
> 
> It does not require authentication, and it does support web discoverability.... we can handle it in a separate PR, but I hope it may assist anyone trying to test this stuff.

So I suppose this is just adding a `serviceProvider` without the `oauth2` element?

**Pull request merged**
