### PR TITLE
Removing code and message from responseSchema40x schemas

### PR DESCRIPTION
**Pull request by nissimsan**
This removes some of the asserted details from the responseSchema40x schemas: 
- `code` which seems redundant with the actual status code (see https://github.com/w3c-ccg/traceability-interop/issues/381).
- the precise error message, which is also redundant as it just describes the generic error http error.

### CODE REVIEW

**Review by brownoxford — COMMENTED** [review]
These values in the postman suite are auto-generated via GitHub workflow using the `tests/update_conformance_schemas.sh` script. Any desired changes should be made to the OpenAPI schema directly.

I would hold off on removing any `code` properties from response definitions pending the outcome of the discussion in https://github.com/w3c-ccg/traceability-interop/issues/381

I do not recommend removing the `message` property. This should be customizable with more specific pre-defined errors. For example, in [did.yml](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/resources/did.yml), we override the Bad Request message with something more specific.

While we do have the `details` parameter in error responses, that is a completely optional item that is left up to implementors to fill out with a helpful message. We added the 'message' property so that we could have some way of enforcing a more generic (but still helpful) error response text.

**Review by OR13 — APPROVED** [review]

**Review by brownoxford — CHANGES_REQUESTED** [review]
These changes must be made in the OpenAPI schema yml files, not directly in the schemas embedded into the postman collection. Also note that you have removed the message overrides in addition to the code - we need to keep those in order to enforce the message text.

**Comment by nissimsan** [comment]
I will update this.

**Comment by nissimsan** [comment]
Updated now in the OAS and keeping the message.

**Review by brownoxford — APPROVED** [review]
LGTM

**Review by mkhraisha — APPROVED** [review]

**Pull request merged**
