### PR TITLE
refactor: initial commit to start draft PR for postman test refactoring

### PR DESCRIPTION
**Pull request by brownoxford**
This draft PR is a work in progress towards refactoring existing postman tests into more easily understood units that can be run separately or wired together as a more complete integration test suite.

The intention here is to develop these new tests in a separate folder and then replace the original folder in the final PR. A basic outline of what will be done is:

1. Refactor existing tests
2. Create appropriate documentation
3. Replace legacy tests

Commits are likely to be frequent, there may be the occasional force-push to clean up, and nothing in the old tests is sacred, including the format of the provider JSON file. Please let me know if you want to be notified directly with a list of changes when I update this PR.

### CODE REVIEW

**Comment by brownoxford** [comment]
Ping @OR13 @mprorock

**Comment by mprorock** [comment]
great direction - can we get spaces out of filenames?

**Review by OR13 — CHANGES_REQUESTED** [review]
no spaces in file names.

the rest looks very clean.

**Comment by brownoxford** [comment]
**Progress Update**
Existing Postman tests have all been refactored into the `tests-postman-wip` folder. Each test is separated into a subfolder in order to store the test runner code, postman collection, and (yet to be written) documentation in the same place.

Next steps are to fully document these existing tests before moving on to add new tests based on the spec.

**Review by OR13 — APPROVED** [review]

**Comment by brownoxford** [comment]
The initial work of refactoring existing tests into separate and easily manipulated postman collections is complete. The next steps outlines above still need to be completed, but I would suggest we move that work into new issues and PRs to keep this PR from growing too large.

**Review by OR13 — APPROVED** [review]

**Comment by TallTed** [comment]
> I would suggest we move that work into new issues and PRs to keep this PR from growing too large

Indeed... Much of the discussion/tracking on this PR should properly have been done in an issue, for which this PR would be a step towards resolution. I encourage making that shift ASAP.

**Pull request merged**
