### PR TITLE
OAS /presentations example

### PR DESCRIPTION
**Pull request by nissimsan**
- The /presentations OAS example has a simple Presentation.yml, this changes it to TraceablePresentation.yml
- Adds a basic Holder.yml to the schema
- Simplifies the VC contained in the example 
- Minor workflow def fix

### CODE REVIEW

**Comment by nissimsan** [comment]
Ref https://github.com/w3c-ccg/traceability-interop/issues/554

**Review by mkhraisha — APPROVED** [review]

**Comment by nissimsan** [comment]
@nissimsan , please add the comma and merge out of band.

**Comment by nissimsan** [comment]
Fixed the missing comma. Merging as agreed.

**Comment by nissimsan** [comment]
Closes #554

**Pull request merged**
