### PR TITLE
chore: remove `alsoKnownAs` from OpenAPI spec

### PR DESCRIPTION
**Pull request by brownoxford**
This PR removes references to `alsoKnownAs` from the OpenAPI spec in this repo.

References #389

### CODE REVIEW

**Review by nissimsan — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Review by OR13 — COMMENTED** [review]
Do we need to update the respec document as well?

**Comment by nissimsan** [comment]
Let's make sure to talk this over next week before merging.

**Review by OR13 — CHANGES_REQUESTED** [review]
update respec document as well see....

Screen Shot 2022-09-13 at 12 49 40 PM

**Comment by brownoxford** [comment]
> update respec document as well see....

Agreed. This is the last of four checkbox items in #389 that needs to be addressed.

**Review by mkhraisha — APPROVED** [review]

**Pull request merged**
