### PR TITLE
Revocation error test

### PR DESCRIPTION
**Pull request by nissimsan**
Checks for errors pre and post revocation. 

(Note that verifiable_credential_id is missing, fixed in https://github.com/w3c-ccg/traceability-interop/pull/159)

### CODE REVIEW

**Review by brownoxford — CHANGES_REQUESTED** [review]
This change in the testing causes a drift from the defined spec, which indicates that a verification response includes only a boolean `verified` property.

https://github.com/w3c-ccg/traceability-interop/blob/main/docs/openapi/schemas/VerificationResult.yml

This is related to #41, and we should probably wait until that is resolved before we change the tests.

**Comment by nissimsan** [comment]
[Here](https://github.com/w3c-ccg/traceability-interop/pull/168)'s an update to the response object. It should unblock this - ref our discussion yesterday, @mprorock , @brownoxford .

**Comment by OR13** [comment]
conflicts exist

**Comment by nissimsan** [comment]
Merging, ref agreement yesterday. It implements https://github.com/w3c-ccg/traceability-interop/pull/168

**Pull request merged**
