### PR TITLE
Removing conformance

### PR DESCRIPTION
**Pull request by nissimsan**
This removes Conformance and conformance-like parts of Interop. Closes https://github.com/w3c-ccg/traceability-interop/issues/631.

### CODE REVIEW

**Review by OR13 — APPROVED** [review]
This is an important step towards adding tests that reflect the current interoperability profile we are aiming to document and support.

We must remove what is stale and not relevant, and add tests to cover the latest requirements

**Review by mkhraisha — APPROVED** [review]

**Review by rhofvendahl — APPROVED** [review]

**Review by brentzundel — APPROVED** [review]

**Comment by PatStLouis** [comment]
@nissimsan @OR13 I've just opened a PR for BCGov's implementation. Since there was a portion of the funding that went towards demonstrating conformance and interop with the specification, I would ask to keep the conformance actions in for a couple more weeks until we can generate a report with our implementation in. This will help us request more funding from the parties involved.

While the report is not significative of the current state of the specification it is representative of the state when the work began. These reports are valuable to demonstrate our compliance.

Otherwise I'm on board with removing these tests after this request has been fulfilled as previously discussed.

Thank you for understanding.

**Comment by mkhraisha** [comment]
This PR has sufficient approvals, pending a final conformance report that incorporates BC gov's wishes @PatStLouis to circle back hopefully next week so we can merge it in.

**Comment by mkhraisha** [comment]
Please merge this when conflicts have been resolved!

**Comment by PatStLouis** [comment]
We are happy with the results, thank you for delaying the removal of conformance testing! Happy to have this merged in

**Pull request merged**
