### PR TITLE
Adding issuance of a GS1/non-trace vocab VC to interop

### PR DESCRIPTION
**Pull request by nissimsan**
This adds issuance of a GS1 VC to the interop report and is intended to close https://github.com/w3c-ccg/traceability-interop/issues/552. 

There are several point I think should be discussed before we progress with this: 
1. I skipped the DID discovery request which we do on the other interop tests - I believe that is outdated? If agreed, then let's make issues to purge this outdated part from the repo entirely. 
2. I just copied over the tests from issuance. Should we be making more dedicated tests?
3. Question to GS1: we can issue either a type `KeyCredential` or `GS1KeyCredential`. I used the former, which is how it looks in the latest spec version - but it'd be nice with a thumbs up on that.  
4. Heads up: this is the first test on Interop to use CredentialStatusList2021.

### CODE REVIEW

**Comment by nissimsan** [comment]
Thoughts from GS1 before potentially merging?

**Comment by nissimsan** [comment]
@paulfdietrich, @tsnyder-gs1us, I'd appreciate you guys' view on this before teeing it up for merging.

**Comment by tsnyder-gs1us** [comment]
KeyCredential is the correct credential type. Let me download the postman collection and test things locally.

**Comment by tsnyder-gs1us** [comment]
The structure of the GS1 Key Credential looks good.  A couple of observations, the GS1 credentials license defines a credential chain: Where the data credential points to the key credential and the key points to the company prefix credential, and then the company prefix links back to the prefix credential issued by GS1 Global. 

In your example KeyCredential: The extendsCredential field needs to point back to the ID of the company prefix credential, the credential subject (KeyCredential) id field contains a GS1 Digital Link with a GTIN value (or GLN), this GTIN value needs to be based on the Company Prefix from the extended credential.  The issuer for the key and data credential must be the subject of the extended Company Prefix. 

Feel free to contact  @paulfdietrich or myself if you have any questions.

**Comment by nissimsan** [comment]
@tsnyder-gs1us, you are referring to `"extendsCredential": "urn:uuid:{{$randomUUID}}"`, right? I changed that now to:

``` 
 "credentialSubject": {
 "id": "https://id.gs1.org/01/07541234555551",
 "extendsCredential": "https://id.gs1.org/01/075412345"
 },
``` 

This indeed implies a GTIN DL. Strictly speaking, I think the urn was valid. It could just as well reference a "parent" credential with the prefix in it. For example, the value in the spec is `"extendsCredential": "did:example:b6d13abe-464d-4bb9-a568-b6d81efd57e3"`

**Comment by nissimsan** [comment]
@tsnyder-gs1us , will you review my updates, pls? Would appreciate a thumbs up before we merge.

**Review by brownoxford — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Comment by nissimsan** [comment]
@tsnyder-gs1us, how is this looking?

**Comment by tsnyder-gs1us** [comment]
@nissimsan one update. Only the credential subject ID should be a GS1 digital link URL. The extendsCredential 
URL is not a valid GS1 digital link. Instead set the extendsCredential to a did:key or urn:uuid.

 "credentialSubject": {
 "id": "https://id.gs1.org/01/07541234555551",
 "extendsCredential": "https://id.gs1.org/01/075412345" -- Not a Valid GS1 digital link
 },

**Review by mkhraisha — APPROVED** [review]

**Pull request merged**
