### PR TITLE
Remove `credentials_issue:credential.id:missing` and `credentials_verify:vc:id:missing` test

### PR DESCRIPTION
**Pull request by ipbyrne**
This test requires an id to be present in the VC when it's sent to /credentials/issue but the VC-API spec implicitly states this field is not required (https://w3c-ccg.github.io/vc-api/#issue-credential), so we are again putting people in a position where their API can only conform to one or the other.

for: https://github.com/w3c-ccg/traceability-interop/issues/512#issuecomment-1428045434

### CODE REVIEW

**Review by OR13 — APPROVED** [review]
See:

- https://github.com/w3c/vc-data-model/issues/1031
- https://w3c-ccg.github.io/vc-api/#issue-credential

`credential.id` SHOULD be optional.

The response from the api is a `verifiable credential` which MUST have an `id`, according to the `trace-interop profile`, and MAY have an `id` according to the `vc-api` and the `vc-data-model`.

**Comment by brownoxford** [comment]
@OR13 We decided that `credential.id` MUST be present in a request to `/credentials/issue`, see #468

**Comment by OR13** [comment]
I realize that, but see the formal work items for the justification.

**Comment by brownoxford** [comment]
> I realize that, but see the formal work items for the justification.

I don't fully follow you here, can you please elaborate?

**Comment by OR13** [comment]
@brownoxford 

https://github.com/w3c-ccg/traceability-interop/pull/519#pullrequestreview-1295782357

https://github.com/w3c/vc-data-model/issues/1031

**Review by brownoxford — CHANGES_REQUESTED** [review]
The request bodies for credential verification tests with bad requests are generated by the `update_conformance_vcs.js` script so that the mutated credentials can have a valid signature.

If we remove the `credentials_verify:vc:id:missing` test, we will also need to modify `update_conformance_vcs.js` so that it does not try to generate the signed request body for that test.

You will want to remove the following code block from that script:
```
  {
    const description = 'vc:id:missing';
    const credentialMutator = (credential) => {
      const doc = klona(credential);
      delete doc.id;
      return doc;
    };
    sampleVCs.set(description, await addProof({ credentialMutator }));
  }
```

**Review by brownoxford — APPROVED** [review]

**Review by mkhraisha — APPROVED** [review]

**Pull request merged**
