### PR TITLE
DID Discovery

### PR DESCRIPTION
**Pull request by nissimsan**
This introduces an authenticated DID discovery call before calling `/ did.json`. This enables support for multi tenant platforms. 

Fixes https://github.com/w3c-ccg/traceability-interop/issues/377

### CODE REVIEW

**Comment by nissimsan** [comment]
We also need to fix `getIssuerId`. But let's do it stepwise and start from here.

**Review by BenjaminMoe — APPROVED** [review]

**Review by brownoxford — COMMENTED** [review]
I would like to hold off on this change pending further discussion.

**Comment by nissimsan** [comment]
@brownoxford, sure happy to hold off on this - it's important that we all get aligned on this.

**Comment by BenjaminMoe** [comment]
- Single tenant hosing
- Multi tenant hosting 

We want to have a diagram around this in the respec document that covers the cases that we're interested in.

**Comment by brownoxford** [comment]
Discussed on call, consensus is to update respec first, then continue discussion on this PR.

**Pull request closed without merging**
