### PR TITLE
chore: update DID resolution endpoint to match postman testing

### PR DESCRIPTION
**Pull request by brownoxford**
Spoke offline with @OR13 about updating the DID resolution endpoint path to match what is being tested in the postman tests:

- Old: `/{did}`
- New: `/identifiers/{did}`

### CODE REVIEW

**Comment by mkhraisha** [comment]
The endpoint will then be `example.org.com/123/identifiers/` from `example.org.com/123`? why do we need to add the extra identifiers endpoint?

**Comment by OR13** [comment]
@mkhraisha see https://w3c-ccg.github.io/did-resolution/#example-0 ... we are aligning with a convention here.

**Comment by mkhraisha** [comment]
Looks good, can we update the [documentation](https://github.com/w3c-ccg/traceability-interop/blob/main/docs/discovery.md) in this PR too.

**Comment by brownoxford** [comment]
I added #115 to track addition of a section regarding the DID resolution endpoint

**Review by mkhraisha — APPROVED** [review]

**Review by OR13 — APPROVED** [review]

**Review by mprorock — APPROVED** [review]
approved with note to fix conflicts

**Pull request merged**
