### PR TITLE
Remove negative tests for context object items

### PR DESCRIPTION
**Pull request by PatStLouis**
These 2 tests are in contradiction with the VC 1.1 data model spec.

Addresses #624

### CODE REVIEW

**Review by nissimsan — APPROVED** [review]
Seems like a good catch. Well done.

**Comment by nissimsan** [comment]
@brownoxford, would love your input on this.

**Comment by brownoxford** [comment]
In order to do this, we should first update the relevant schemas, as they currently specify array of string for `@context`.

**Review by brownoxford — CHANGES_REQUESTED** [review]
In order to do this, we should first update the relevant schemas, as they currently specify array of string for `@context`.

**Comment by TallTed** [comment]
Do these contradict or agree with VCDM 2.0?

**Comment by PatStLouis** [comment]
@brownoxford I will look at including this change along in this PR

**Review by mkhraisha — APPROVED** [review]
assuming chris' objection is included

**Comment by mkhraisha** [comment]
@PatStLouis any updates

**Comment by PatStLouis** [comment]
closing since conformance testing will become out of scope for this specification

**Pull request closed without merging**
