### PR TITLE
removes requirement of messages to be a specific enum

### PR DESCRIPTION
**Pull request by mkhraisha**
We had a prior agreement on a call, that we should specify the shape of the errors, but we do not need to specify the exact value of the error message.

### CODE REVIEW

**Review by BenjaminMoe — APPROVED** [review]

**Comment by BenjaminMoe** [comment]
1. Is this valid syntax. For `message` i would expect `type: string` with an `example`
2. Do we want to use `allOf`? Seems like we want to have a fixed structure even if we don't have a specific message for the enum. 
3. 
```
description: Bad Request
content:
  application/json:
    schema:
      allOf:
        - $ref: '../schemas/Error.yml'
        - type: object
          properties:
            message
```

**Review by brownoxford — CHANGES_REQUESTED** [review]
@BenjaminMoe is on the right track here. All of these errors in `docs/openapi/responses` that make use of `allOf` are overriding the `message` property of `Error.yml` to change it from `string` to `enum`. The `allOf` is no longer needed.

**Comment by mkhraisha** [comment]
@brownoxford @BenjaminMoe lmk if that fixes it

**Review by brownoxford — APPROVED** [review]
Thanks Mahmoud!

**Review by nissimsan — APPROVED** [review]

**Pull request merged**
